### ISSUE TITLE
MacOS vs iPhone - Cross Product Sync Test

### ISSUE THREAD

**Issue by LaurenWags** [brave/sync#117]
# Cross Product Test Matrix

## Laptop vs iOS (iPhone)
Setup
- [x] Prior to sync, add folders and bookmarks to laptop and iPhone.
- [x] Create sync group on laptop, join sync group on iPhone

Adding bookmarks and folders
- [x] Add bookmark to bookmarks bar on Laptop. Verify synced to iPhone.
- [x] Add bookmark to Mobile Bookmarks on iPhone. Verify synced to Laptop.
- [x] Add Folder to bookmarks bar on Laptop. Add bookmarks into folder. Verify synced to iPhone.
- [x] Add Folder to bookmarks bar on iPhone. Add bookmarks into folder. Verify synced to Laptop.

Edit bookmarks and folders created on same laptop
- [x] On Laptop, edit a bookmark created on Laptop. Verify change is synced to iPhone.
- [x] On iPhone, edit a bookmark created on iPhone. Verify change is synced to Laptop.
- [x] On Laptop, edit a folder created on Laptop. Verify change is synced to iPhone.
- [x] On iPhone, edit a folder created on iPhone. Verify change is synced to Laptop.
- [ ] On Laptop, move a bookmark created on Laptop A. Verify change is synced to iPhone. (https://github.com/brave/sync/issues/111)
- [ ] On Laptop, move a folder created on Laptop. Verify change is synced to iPhone. (https://github.com/brave/sync/issues/107)

Delete bookmarks and folders created on same laptop
- [x] On Laptop, delete a bookmark created on Laptop. Verify change is synced to iPhone.
- [x] On iPhone, delete a bookmark created on iPhone. Verify change is synced to Laptop.
- [x] On Laptop, delete a folder created on Laptop. Verify change is synced to iPhone.
- [x] On iPhone, delete a folder created on iPhone. Verify change is synced to Laptop.

Edit bookmarks and folders created on a different laptop
- [x] On Laptop, edit a bookmark created on iPhone. Verify change is synced to iPhone.
- [x] On iPhone, edit a bookmark created on Laptop. Verify change is synced to Laptop.
- [x] On Laptop, edit a folder created on iPhone. Verify change is synced to iPhone.
- [x] On iPhone, edit a folder created on Laptop. Verify change is synced to Laptop.
- [ ] On Laptop, move a bookmark created on iPhone. Verify change is synced to iPhone. (https://github.com/brave/sync/issues/111)
- [ ] On Laptop, move a folder created on iPhone. Verify change is synced to iPhone. (https://github.com/brave/sync/issues/107)

Delete bookmarks and folders created on a different laptop
- [x] On Laptop, delete a bookmark created on iPhone. Verify change is synced to iPhone.
- [x] On iPhone, delete a bookmark created on Laptop. Verify change is synced to Laptop.
- [x] On Laptop, delete a folder created on iPhone. Verify change is synced to iPhone.
- [x] On iPhone, delete a folder created on Laptop. Verify change is synced to Laptop.

Importing
- [ ] On Laptop, import bookmarks. Verify change is synced to iPhone. (https://github.com/brave/sync/issues/112)

Toggle Sync
- [x] On Laptop, toggle sync off in Preferences. Add or edit a bookmark. Verify change is not synced to iPhone.
- [x] On Laptop, while sync is still off, add or edit a folder. Verify change is not synced to iPhone.
- [x] On iPhone, while sync is still off on Laptop, add or edit a bookmark. Verify change is not synced to Laptop.
- [x] On iPhone, while sync is still off on Laptop, add or edit a folder. Verify change is not synced to Laptop.
- [x] On Laptop, toggle sync back on in Preferences. Verify changes made are synced.

Network Outage
- [x] Disconnect iPhone from network. On Laptop, make some changes to bookmarks/folders. Verify change is not synced to iPhone. Reconnect iPhone to network. Verify changes are synced.

Power off Device
- [x] Power off iPhone. On Laptop, make some changes to bookmarks/folders. Power on iPhone. Verify changes are synced.
