### ISSUE TITLE
Missing bookmarks tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/sync#146]
#Pre-sync import scenario

## simple case ( < 50 boomarks )
 - [ ]  laptop - laptop scenario
 - [ ] laptop - iOS scenario
 - [ ] laptop - android scenario

**Comment by LaurenWags** [comment]
Post-Sync Import Scenario - Complex (1500 bookmarks with nested folders) - laptop to android: all 1500 bookmarks synced to android. I then added an iOS device (iPhone) to the sync group once sync on Android was complete. As of now, iPhone only has approximately 400 bookmarks.

**Comment by alexwykoff** [comment]
# Post-sync import laptop - iOS scenario
laptop version : 0.18.5
iOS version : 1.4 (17.07.13.15)
created sync group on laptop, joined iPad
attempted to import with laptop and iOS app open
[brave_sorted_ish.html.zip](https://github.com/brave/sync/files/1153788/brave_sorted_ish.html.zip)

multiple errors on sync console, many thousands of bookmarks missing
<img width="1150" alt="screen shot 2017-07-17 at 2 36 06 pm" src="https://user-images.githubusercontent.com/1434040/28286745-d760a3f4-6afe-11e7-8c6e-644a1eef3f5a.png">

**Comment by alexwykoff** [comment]
# Pre-sync import laptop - iOS scenario
laptop version : 7b31653eb555ba8f00395cd593f9b948ada296fe
iOS version : 1.4 (17.07.13.15)
created sync group on laptop, joined iPad
attempted to import with laptop and iOS app open
[brave_sorted_ish.html.zip](https://github.com/brave/sync/files/1153788/brave_sorted_ish.html.zip)

No errors on laptop sync console. 

While it cannot be conclusively proven, it appears as though the bookmarks have all synced to the iOS device. However the order is not consistent.
<img width="1198" alt="screen shot 2017-07-17 at 3 00 08 pm" src="https://user-images.githubusercontent.com/1434040/28287339-e8848e8c-6b00-11e7-92fe-543304fcfbd6.png">
vs
![img_0282](https://user-images.githubusercontent.com/1434040/28287350-eea92e3a-6b00-11e7-8e4d-1c2383aed557.PNG)

**Comment by alexwykoff** [comment]
# Post-sync import laptop - iOS scenario (simple case)
laptop version : 7b31653eb555ba8f00395cd593f9b948ada296fe
iOS version : 1.4 (17.07.13.15)
created sync group on laptop, joined iPad
attempted to import with laptop and iOS app open
[brave_sorted_simple.html.zip](https://github.com/brave/sync/files/1153908/brave_sorted_simple.html.zip)

No errors on sync console.

All bookmarks appeard on iOS, but the order wasn't maintained.

**Comment by alexwykoff** [comment]
# Pre-sync import laptop - iOS scenario (simple case)
laptop version : 7b31653eb555ba8f00395cd593f9b948ada296fe
iOS version : 1.4 (17.07.13.15)
created sync group on laptop, joined iPad
attempted to import with laptop and iOS app open
[brave_sorted_simple.html.zip](https://github.com/brave/sync/files/1153908/brave_sorted_simple.html.zip)

No errors on sync console.

All bookmarks appeard on iOS, but the order wasn't maintained. 

It should be noted that iOS order was different from the Post-sync simple case. From this, I would intuit that either the order in which iOS is pulling sync records is random or the order in which the records are being added to the sync group is random.

**Comment by LaurenWags** [comment]
Pre-Sync Import Laptop-Android scenario (simple case)
Laptop version: 0.17.17 (dbc3c4d96029de2eb64735d31c0067ae0b6f878a)
Android version 1.0.25
Created sync group on laptop, imported 49 bookmarks (see brave_sorted_simple.html.zip from comment above), joined sync group on Android.
No errors on sync console.
All bookmarks appeared on Android, order was maintained.

**Comment by srirambv** [comment]
## Pre-Sync import Laptop-Laptop scenario (complex case)

Laptop Pyramid 0 : https://github.com/brave/browser-laptop/commit/e4e0cec453dab14f1b981800fd5f3b7b9ce0c772
Laptop Pyramid 1 : https://github.com/brave/browser-laptop/pull/9988/commits/7b31653eb555ba8f00395cd593f9b948ada296fe

Import 5k bookmarks file on Pyramid 1 
Enable Sync on Pyramid 0
Sync with Pyramid 1 using keywords
No errors on Sync console
All bookmarks appeared on Pyramid 0
Bookmark structure maintained as it is
[19_07_2017.zip](https://github.com/brave/sync/files/1158956/19_07_2017.zip)
![image](https://user-images.githubusercontent.com/17010094/28365253-b3866338-6c7f-11e7-80e8-558490418ae0.png)

**Comment by srirambv** [comment]
## Post-Sync import Laptop-Laptop scenario (complex case)

Laptop Pyramid 0 : brave/browser-laptop@7b31653
Laptop Pyramid 1 : brave/browser-laptop@e4e0cec

Enable Sync on Pyramid 0
Sync Pyramid 1 with Pyramid 0 using sync code
No errors on Sync console
All bookmarks appeared on Pyramid 1
Bookmark structure maintained as it is
![image](https://user-images.githubusercontent.com/17010094/28366650-90a26d20-6c85-11e7-8352-c3421551619f.png)
![image](https://user-images.githubusercontent.com/17010094/28366673-a4d17f0c-6c85-11e7-8213-14da86a0de6d.png)

**Comment by srirambv** [comment]
## Pre-Sync import Laptop-Laptop scenario (simple case) - ~300 Bookmarks
Laptop Pyramid 0 : brave/browser-laptop@7b31653
Laptop Pyramid 1 : brave/browser-laptop@e4e0cec

Import bookmarks file with ~300 bookmarks on Pyramid 0 
Enable Sync on Pyramid 0
Sync with Pyramid 1 using keywords
No errors on Sync console
All bookmarks appeared on Pyramid 0
Bookmark structure maintained as it is
![image](https://user-images.githubusercontent.com/17010094/28370424-305b7526-6c92-11e7-9123-b6769a03d239.png)

**Comment by srirambv** [comment]
##Post-Sync import Laptop-Laptop scenario (simple case) - ~300 Bookmarks

Laptop Pyramid 0 : brave/browser-laptop@7b31653
Laptop Pyramid 1 : brave/browser-laptop@e4e0cec

Enable Sync on Pyramid 0
Sync with Pyramid 1 using keywords
Import bookmarks file with ~300 bookmarks on Pyramid 0
No errors on Sync console
All bookmarks appeared on Pyramid 0
Bookmark structure maintained as it is
![image](https://user-images.githubusercontent.com/17010094/28371566-3f715dca-6c95-11e7-8754-5344a8022ae1.png)

**Comment by LaurenWags** [comment]
Post-Sync import Laptop-Laptop scenario (complex case)

Laptop Pyramid 0 : brave/browser-laptop@e4e0cec (MacOS)
Laptop Pyramid 1 : brave/browser-laptop@e4e0cec (Linux - Ubuntu)

Enable Sync on Pyramid 0
Sync Pyramid 1 with Pyramid 0 using sync code
Import 6000+ bookmarks on Pyramid 0, Pyramid 1 was left open
No errors on Sync console
Not all bookmarks were synced to Pyramid 1
Some folders missing on Pyramid 1 also.

[numbered_bookmark_file.html.zip](https://github.com/brave/sync/files/1159590/numbered_bookmark_file.html.zip)

![screen shot 2017-07-19 at 11 24 09 am](https://user-images.githubusercontent.com/28145373/28375341-38066b86-6c75-11e7-8427-234c1e907c58.png)

**Comment by LaurenWags** [comment]
Pre-sync import scenario - Complex case ( >6000 bookmarks, nested folders)
Pyramid 0 - MacOS (0.18.10)
Pyramid 1 - Android (Nexus Galaxy S4)
Imported  > 6k bookmarks with nested folders. Enabled sync on laptop. Joined sync group on Android. All bookmarks synced to Android.

**Comment by srirambv** [comment]
## Post Sync Scenario - Complex Case (>6k bookmarks, nested folders)

Pyramid 0 - iPhone 7+ (iOS 10.3.3)  Beta ver 1.4(17.07.20.16)
Pyramid 1 - Laptop Windows 10 x64 (https://github.com/brave/browser-laptop/commit/7b31653)
Enable Sync on iPhone -> Get sync code
Add laptop to sync group using the code words from iPhone
Import >6K bookmarks file on Laptop
Bookmarks failed to show up on iOS due to https://github.com/brave/browser-ios/issues/983
Kill and restart app, bookmarks synced
Last nested folder is not shown on top but somewhere in between bookmarks
![image](https://user-images.githubusercontent.com/17010094/28537600-620c8cbc-70a3-11e7-83f4-82f557f34834.png)

**Comment by LaurenWags** [comment]
Post-sync import scenario - Simple case ( <50  bookmarks)

Pyramid 0 - MacOS (0.18.10)
Pyramid 1 - Android (Nexus Galaxy S4)
Enabled sync on laptop. Joined sync group on Android. Imported less than 50 bookmarks. All bookmarks synced to Android.

**Comment by LaurenWags** [comment]
Post-sync import scenario - Complex case ( >6000 bookmarks, nested folders)

Pyramid 0 - MacOS (0.18.10)
Pyramid 1 - Android (Nexus Galaxy S4)
Enabled sync on laptop. Joined sync group on Android. Imported > 6k bookmarks with nested folders. All bookmarks synced to Android.

**Comment by LaurenWags** [comment]
Post Sync Scenario - Complex Case (>6k bookmarks, nested folders)

Pyramid 0 - MacOS (0.18.10, 73465bb)
Pyramid 1 - iPad (iOS 10.3.1) Beta ver 1.4(17.07.20.16)
Enable Sync on Laptop -> Get sync code
Add iPad to sync group using QR Code.
Import >6K bookmarks file on Laptop from Firefox.
Bookmarks failed to show up on iOS due to brave/browser-ios#983
Kill and restart app, bookmarks synced
Last nested folder is not shown on top but somewhere in between bookmarks

Confirmed findings from @srirambv in https://github.com/brave/sync/issues/146#issuecomment-317507040
